---
--- Core components
---
HOLOHUD2.AddCSLuaFile( "components/blur.lua" )
HOLOHUD2.AddCSLuaFile( "components/color.lua" )
HOLOHUD2.AddCSLuaFile( "components/colorselector.lua" )
HOLOHUD2.AddCSLuaFile( "components/colorranges.lua" )
HOLOHUD2.AddCSLuaFile( "components/panel.lua" )
HOLOHUD2.AddCSLuaFile( "components/text.lua" )
HOLOHUD2.AddCSLuaFile( "components/separator.lua" )
HOLOHUD2.AddCSLuaFile( "components/number.lua" )
HOLOHUD2.AddCSLuaFile( "components/icon.lua" )
HOLOHUD2.AddCSLuaFile( "components/bar.lua" )
HOLOHUD2.AddCSLuaFile( "components/baseprogressbar.lua" )
HOLOHUD2.AddCSLuaFile( "components/progressbar.lua" )
HOLOHUD2.AddCSLuaFile( "components/progressicon.lua" )
HOLOHUD2.AddCSLuaFile( "components/dotline.lua" )
HOLOHUD2.AddCSLuaFile( "components/layeredbar.lua" )
HOLOHUD2.AddCSLuaFile( "components/damagebar.lua" )
HOLOHUD2.AddCSLuaFile( "components/animatedpanel.lua" )
HOLOHUD2.AddCSLuaFile( "components/ecg.lua" )
HOLOHUD2.AddCSLuaFile( "components/ammoicon.lua" )
HOLOHUD2.AddCSLuaFile( "components/ammotray.lua" )
HOLOHUD2.AddCSLuaFile( "components/compass.lua" )
HOLOHUD2.AddCSLuaFile( "components/clock.lua" )
HOLOHUD2.AddCSLuaFile( "components/graph.lua" )
HOLOHUD2.AddCSLuaFile( "components/gauge.lua" )
HOLOHUD2.AddCSLuaFile( "components/damageindicator.lua" )
HOLOHUD2.AddCSLuaFile( "components/damagearrow.lua" )
HOLOHUD2.AddCSLuaFile( "components/itempickup.lua" )
HOLOHUD2.AddCSLuaFile( "components/ammopickup.lua" )
HOLOHUD2.AddCSLuaFile( "components/weaponicon.lua" )
HOLOHUD2.AddCSLuaFile( "components/weaponpickup.lua" )
HOLOHUD2.AddCSLuaFile( "components/hazard.lua" )
HOLOHUD2.AddCSLuaFile( "components/radar.lua" )
HOLOHUD2.AddCSLuaFile( "components/elevation.lua" )
HOLOHUD2.AddCSLuaFile( "components/deathnotice.lua" )
HOLOHUD2.AddCSLuaFile( "components/quickinfobar.lua" )
HOLOHUD2.AddCSLuaFile( "components/revcounter.lua" )
HOLOHUD2.AddCSLuaFile( "components/messagelog.lua" )
HOLOHUD2.AddCSLuaFile( "components/bracket.lua" )

---
--- Auxiliary components.
---
HOLOHUD2.AddCSLuaFile( "components/numericdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/numericicondisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/iconmeterdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/meterdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/layeredmeterdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/counterdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/graphdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/graphunitdisplay.lua" )
HOLOHUD2.AddCSLuaFile( "components/inlinecounter.lua" )