---
--- Register contribution types.
---

HOLOHUD2.credits.Register( "code", "icon16/application_xp_terminal.png", "#holohud2.credits.code" )
HOLOHUD2.credits.Register( "design", "icon16/image_edit.png", "#holohud2.credits.design" )
HOLOHUD2.credits.Register( "art", "icon16/palette.png", "#holohud2.credits.art" )
HOLOHUD2.credits.Register( "sound", "icon16/sound.png", "#holohud2.credits.sounds" )

HOLOHUD2.credits.Register( "test", "icon16/computer_error.png", "#holohud2.credits.test" )
HOLOHUD2.credits.Register( "bugfix", "icon16/bug.png", "#holohud2.credits.bugfix" )
HOLOHUD2.credits.Register( "optimization", "icon16/wrench.png", "#holohud2.credits.optimization" )
HOLOHUD2.credits.Register( "feature", "icon16/brick_add.png", "#holohud2.credits.feature" )
HOLOHUD2.credits.Register( "plugin", "icon16/plugin.png", "#holohud2.credits.plugin" )
HOLOHUD2.credits.Register( "misc", "icon16/comment.png", "#holohud2.credits.misc" )

HOLOHUD2.credits.Register( "locale_bg", "flags16/bg.png", "#holohud2.credits.locale_bg" )
HOLOHUD2.credits.Register( "locale_cs", "flags16/cz.png", "#holohud2.credits.locale_cs" )
HOLOHUD2.credits.Register( "locale_da", "flags16/dk.png", "#holohud2.credits.locale_da" )
HOLOHUD2.credits.Register( "locale_de", "flags16/de.png", "#holohud2.credits.locale_de" )
HOLOHUD2.credits.Register( "locale_el", "flags16/gr.png", "#holohud2.credits.locale_el" )
HOLOHUD2.credits.Register( "locale_en-PT", "flags16/england.png", "#holohud2.credits.locale_en-PT" )
HOLOHUD2.credits.Register( "locale_es-ES", "flags16/es.png", "#holohud2.credits.locale_es-ES" )
HOLOHUD2.credits.Register( "locale_et", "flags16/ee.png", "#holohud2.credits.locale_et" )
HOLOHUD2.credits.Register( "locale_fi", "flags16/fi.png", "#holohud2.credits.locale_fi" )
HOLOHUD2.credits.Register( "locale_fr", "flags16/fr.png", "#holohud2.credits.locale_fr" )
HOLOHUD2.credits.Register( "locale_he", "flags16/il.png", "#holohud2.credits.locale_he" )
HOLOHUD2.credits.Register( "locale_hr", "flags16/hr.png", "#holohud2.credits.locale_hr" )
HOLOHUD2.credits.Register( "locale_hu", "flags16/hu.png", "#holohud2.credits.locale_hu" )
HOLOHUD2.credits.Register( "locale_it", "flags16/it.png", "#holohud2.credits.locale_it" )
HOLOHUD2.credits.Register( "locale_ja", "flags16/jp.png", "#holohud2.credits.locale_ja" )
HOLOHUD2.credits.Register( "locale_ko", "flags16/kr.png", "#holohud2.credits.locale_ko" )
HOLOHUD2.credits.Register( "locale_lt", "flags16/lt.png", "#holohud2.credits.locale_lt" )
HOLOHUD2.credits.Register( "locale_nl", "flags16/nl.png", "#holohud2.credits.locale_nl" )
HOLOHUD2.credits.Register( "locale_no", "flags16/no.png", "#holohud2.credits.locale_no" )
HOLOHUD2.credits.Register( "locale_pl", "flags16/pl.png", "#holohud2.credits.locale_pl" )
HOLOHUD2.credits.Register( "locale_pt-BR", "flags16/br.png", "#holohud2.credits.locale_pt-BR" )
HOLOHUD2.credits.Register( "locale_pt-PT", "flags16/pt.png", "#holohud2.credits.locale_pt-PT" )
HOLOHUD2.credits.Register( "locale_ru", "flags16/ru.png", "#holohud2.credits.locale_ru" )
HOLOHUD2.credits.Register( "locale_sk", "flags16/sk.png", "#holohud2.credits.locale_sk" )
HOLOHUD2.credits.Register( "locale_sv-SE", "flags16/se.png", "#holohud2.credits.locale_sv-SE" )
HOLOHUD2.credits.Register( "locale_th", "flags16/th.png", "#holohud2.credits.locale_th" )
HOLOHUD2.credits.Register( "locale_tr", "flags16/tr.png", "#holohud2.credits.locale_tr" )
HOLOHUD2.credits.Register( "locale_uk", "flags16/ua.png", "#holohud2.credits.locale_uk" )
HOLOHUD2.credits.Register( "locale_vi", "flags16/vn.png", "#holohud2.credits.locale_vi" )
HOLOHUD2.credits.Register( "locale_zh-CN", "flags16/cn.png", "#holohud2.credits.locale_cn" )
HOLOHUD2.credits.Register( "locale_zh-TW", "flags16/tw.png", "#holohud2.credits.locale_tw" )