HOLOHUD2.hazard.Register( DMG_BURN, surface.GetTextureID( "holohud2/hazards/burn" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_BLAST, surface.GetTextureID( "holohud2/hazards/blast" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_SHOCK, surface.GetTextureID( "holohud2/hazards/shock" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_ENERGYBEAM, surface.GetTextureID( "holohud2/hazards/energybeam" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_DROWN, surface.GetTextureID( "holohud2/hazards/drown" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_PARALYZE, surface.GetTextureID( "holohud2/hazards/paralyze" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_NERVEGAS, surface.GetTextureID( "holohud2/hazards/nervegas" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_POISON, surface.GetTextureID( "holohud2/hazards/poison" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_RADIATION, surface.GetTextureID( "holohud2/hazards/radiation" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_ACID, surface.GetTextureID( "holohud2/hazards/acid" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_DISSOLVE, surface.GetTextureID( "holohud2/hazards/dissolve" ), 64, 64 )
HOLOHUD2.hazard.Register( DMG_SLOWBURN, DMG_BURN, true )
HOLOHUD2.hazard.Register( DMG_PLASMA, DMG_ACID, true )